---
ls:
  .puml: kebab-case
  .md: kebab-case | SCREAMING_SNAKE_CASE

  .conf: kebab-case
  .js: kebab-case
  .json: kebab-case
  .yml: kebab-case
  .yaml: kebab-case

  .java: PascalCase
  .kt: PascalCase
  .sh: kebab-case

  Dockerfile: PascalCase
  Vagrantfile: PascalCase

ignore:
  - .git
  - .idea
  - .vscode
  - node_modules
  - target

  - .dockerignore
  - .env
  - .folderslintrc
  - .gitignore
  - .gitkeep
  - .hadolint.yml
  - .ls-lint.yml
  - .markdownlint.yml
  - .yamllint.yml
  - .pre-commit-config.yaml
  - .releaserc
  - .release.sh
  - .shellcheckrc
